### ISSUE TITLE
Surah Baqarah (V 20) of Abdul Haleem Translation

### ISSUE THREAD

**Issue by muhammadmw** [quran/quran.com-frontend#1037]
**I'm submitting a ...**

- [ x] bug report
- [ ] feature request
- [ ] other

**Current behavior:**

Part of the ayat (2:20) is being translated in the Abdul Haleem Translation.

**Comment by naveed-ahmad** [comment]
Current translation:
> The lightning almost snatches away their sight: whenever it crashes on

Full translation:
> The lightning almost snatches away their sight: whenever it flashes on them they walk on and when darkness falls around them they stand still. If God so willed, He could take away their hearing and sight: God has power over everything.

Ref: https://ia601902.us.archive.org/18/items/TheQuranOxfrdWrldClas/The%20Qur%27an%20%28Oxford%20World%27s%20Clas%20-%20M.%20A.%20S.%20Abdel%20Haleem.pdf

Fixed on staging.

**Comment by muhammadmw** [comment]
The error is still there. 
Could I know how long it will take for the total translation to come up?
