### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:3000

### ISSUE THREAD

**Issue by uslika** [quran/quran.com-frontend#298]
{ error:
   { [Error: connect ECONNREFUSED 127.0.0.1:3000]
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 3000,
     response: undefined },
  type: '@@quran/surahs/LOAD_FAIL' }

**Comment by mmahalwy** [comment]
hmm seeing this problem too. not sure why. looking into it..

**Comment by uslika** [comment]
Thanks im waiting

**Comment by mmahalwy** [comment]
Fixed

**Comment by uslika** [comment]
Not fixed bro.

   ==> 🌎  ENV=undefined
      ==> ✅  Server is listening at http://localhost:8000
      ==> 🎯  API at http://localhost:3000

{ error:
   { [Error: connect ECONNREFUSED 127.0.0.1:3000]
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 3000,
     response: undefined },
  type: '@@quran/surahs/LOAD_FAIL' }
GET / 200 459.157 ms - -
{ error:
   { [Error: connect ECONNREFUSED 127.0.0.1:3000]
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 3000,
     response: undefined },
  type: '@@quran/surahs/LOAD_FAIL' }
{ error:
   { [Error: connect ECONNREFUSED 127.0.0.1:3000]
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 3000,
     response: undefined },
  type: '@@quran/surahs/LOAD_FAIL' }
{ error:
   { [Error: connect ECONNREFUSED 127.0.0.1:3000]
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 3000,
     response: undefined },
  type: '@@quran/surahs/LOAD_FAIL' }
GET / 200 459.157 ms - -
{ error:
   { [Error: connect ECONNREFUSED 127.0.0.1:3000]
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 3000,
     response: undefined },
  type: '@@quran/surahs/LOAD_FAIL' }
{ error:
   { [Error: connect ECONNREFUSED 127.0.0.1:3000]
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 3000,
     response: undefined },
  type: '@@quran/surahs/LOAD_FAIL' }
